audit_header: false
title: "Dayton's Best Real Estate Training"
description: Denise Swick, a top Real Estate Agent in Dayton, shares her own internal real estate agent training for free. Her Real Estate Training, Tips and Advice will help you sell more homes in less time.
show_custom_links: true
custom_links:
  - title: Join Our Team
    url: /join-our-team/
  - title: Events
    url: https://www.eventbrite.com/o/denise-swick-19837853678
  - title: Free Strategy Call
    url: /strategy-call/
  - title: Free Newsletter
    url: /subscribe/

post_ctas:
  events_url: https://www.eventbrite.com/o/denise-swick-19837853678
  events_image: /img/events.jpg
  join_our_team_image: /img/join_our_team_full.jpg

client:
  name: Denise Swick
  title:
  license_number:
  about_markdown: |
    Denise Swick is a nationally respected real estate broker, leading a talent team of professionals to create memorable experiences for her clients. She uses her understanding of the Dayton area, honed with over two decades of working in the area, to devise the best plan of action for buying or selling a home. Her approach is one of honesty and integrity, looking to give each person she works with unforgettable results.

    Her approach to the industry has evolved over time, going from one woman on a mission to developing a team of like-minded individuals with the same drive she possesses. This team approach benefits the people that work with her RE/MAX Performance, providing more attention to every detail of the real estate experience. She is actively involved with each aspect of the business, inspiring and motivating her staff to achieve the best results.
  market: Dayton
  brand: Denise Swick & Company
  brokerage: RE/MAX
  address: 7007 Corporate Way, Dayton, OH 45459
  phone: 937-619-7447
  phone_type: Denise
  phone2: 937-619-7450
  phone2_type: Greg
  email: careers@deniseswick.com
  url: http://www.deniseswick.com

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/Dayton-Real-Estate-Mastermind-2307906606201541/
  linkedin_url:
  gplus_url:
  youtube_url:
  twitter_url:
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: '-- MARKET -- Real Estate Podcast with -- CLIENT NAME --'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- MARKET -- Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in -- MARKET --, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: '-- CLIENT NAME --'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: -- MARKET -- Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#A92D31'
  accent_color: '#103F8D'
  theme_color: '#133775'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

navbar_colors:
  border_bottom:

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: transparent

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
